name: R package CI

on: [push, pull_request]

jobs:
  common-r:
    runs-on: ubuntu-latest
    name: Test package with docker
    container: 
      image: brickmanlab/common-r:dev
      options: --user root -v ${{ github.workspace }}:/commonR:rw
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get package name and version
        run: |
          echo "::set-env name=PACKAGE_NAME::$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"
          echo "::set-env name=PACKAGE_VERSION::$(cat DESCRIPTION | grep 'Version:' | cut -d' ' -f2 )"
        shell: bash

      - name: Build package
        run: cd /commonR && R CMD build .
      
      - name: Check package
        run: R CMD check ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.tar.gz

      - name: Lint package
        run: cd /commonR && Rscript -e 'lintr::lint_package()'"