name: R package CI

on: [push, pull_request]

jobs:
  common-r:
    runs-on: ubuntu-latest
    name: Test package with docker
    container: 
      image: brickmanlab/common-r:dev
      options: --user root -v ${{ github.workspace }}:/commonR:rw
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build package
        run: R CMD build /commonR
      
      - name: Check package
        run: R CMD check /commonR

      - name: Lint package
        run: cd /commonR && Rscript -e 'lintr::lint_package()'"