name: R package CI

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-18.04
      strategy:
        matrix:
          R: [ '3.6.1', '3.6.2' ]
      name: R ${{ matrix.R }} sample
      steps:
        - uses: actions/checkout@v1
        - name: Setup R
          uses: r-lib/actions/setup-r@master
          with:
            r-version: ${{ matrix.R }}
        
        - name: Get package name and version
          run: |
            echo ::set-env name=PACKAGE_NAME::$(echo $GITHUB_REPOSITORY | cut -d"/" -f2)
            echo ::set-env name=PACKAGE_VERSION::$(cat DESCRIPTION | grep "Version:" | cut -d" " -f2 )
          shell: bash

        - name: Build package
          run: R CMD build .
      
        - name: Check package
          run: R CMD check ${{ PACKAGE_NAME }}_${{ PACKAGE_VERSION }}.tar.gz
